# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f3ff4bc3409f1515e1b2ff939d4d77539d497766841604441941fceda8454277076e638796d6add65ede1e4550fab7826ffed03b2eeb5d6be550ce1b42a2be

test:
  secret_key_base: deb1e1ab1984068bd0943e63a02db74ace3df2b93d80ffaa2dda104a20b107b6e675f7365e46a8c22e45054d3d1a540626168e1f8e079522d08fe9388749b34b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
